import React from "react";
import {
  Package,
  Layers,
  Globe,
  Calendar,
  Check,
  X,
  Plus,
  Minus,
  Mail,
  Phone,
  MapPin,
  Users,
  User,
  Building2,
  Briefcase,
  FileText,
  Link,
  Star,
  Heart,
  MessageSquare,
  Settings,
  Shield,
  Bell,
  Camera,
  Image as ImageIcon,
  Video,
  Music,
  DollarSign,
  Euro,
  CreditCard,
  ShoppingCart,
  Tag,
  Bookmark,
  Cpu,
  Database,
  Rocket,
  Zap,
  Wifi,
  Cloud,
  Sun,
  Moon,
  Map,
  Compass,
  GitBranch,
  Github,
  Linkedin,
  Twitter,
} from "lucide-react";

export interface LucideIconOption {
  name: string;
  Icon: React.ComponentType<{ className?: string }>;
  keywords?: string[];
}

// Curated list for efficiency. Add more as your app needs them.
export const LUCIDE_ICON_OPTIONS: LucideIconOption[] = [
  { name: "Package", Icon: Package, keywords: ["box", "product", "service"] },
  { name: "Layers", Icon: Layers, keywords: ["stack", "tiers"] },
  { name: "Globe", Icon: Globe, keywords: ["world", "web", "internet"] },
  { name: "Calendar", Icon: Calendar, keywords: ["date", "schedule"] },
  { name: "Check", Icon: Check, keywords: ["ok", "confirm", "done"] },
  { name: "X", Icon: X, keywords: ["close", "cancel"] },
  { name: "Plus", Icon: Plus, keywords: ["add", "create"] },
  { name: "Minus", Icon: Minus, keywords: ["remove", "subtract"] },
  { name: "Mail", Icon: Mail, keywords: ["email", "message"] },
  { name: "Phone", Icon: Phone, keywords: ["call", "contact"] },
  { name: "MapPin", Icon: MapPin, keywords: ["location", "address"] },
  { name: "Users", Icon: Users, keywords: ["people", "team"] },
  { name: "User", Icon: User, keywords: ["person", "profile"] },
  { name: "Building2", Icon: Building2, keywords: ["org", "company"] },
  { name: "Briefcase", Icon: Briefcase, keywords: ["work", "service"] },
  { name: "FileText", Icon: FileText, keywords: ["doc", "offer", "text"] },
  { name: "Link", Icon: Link, keywords: ["url", "href"] },
  { name: "Star", Icon: Star, keywords: ["favorite", "rating"] },
  { name: "Heart", Icon: Heart, keywords: ["like", "love"] },
  { name: "MessageSquare", Icon: MessageSquare, keywords: ["comment", "chat"] },
  { name: "Settings", Icon: Settings, keywords: ["config", "preferences"] },
  { name: "Shield", Icon: Shield, keywords: ["security", "protect"] },
  { name: "Bell", Icon: Bell, keywords: ["notification", "alert"] },
  { name: "Camera", Icon: Camera, keywords: ["photo"] },
  { name: "Image", Icon: ImageIcon, keywords: ["picture"] },
  { name: "Video", Icon: Video, keywords: ["movie", "media"] },
  { name: "Music", Icon: Music, keywords: ["audio", "song"] },
  { name: "DollarSign", Icon: DollarSign, keywords: ["usd", "price"] },
  { name: "Euro", Icon: Euro, keywords: ["eur", "price"] },
  { name: "CreditCard", Icon: CreditCard, keywords: ["payment"] },
  { name: "ShoppingCart", Icon: ShoppingCart, keywords: ["ecommerce", "buy"] },
  { name: "Tag", Icon: Tag, keywords: ["label"] },
  { name: "Bookmark", Icon: Bookmark, keywords: ["save"] },
  { name: "Cpu", Icon: Cpu, keywords: ["tech", "hardware"] },
  { name: "Database", Icon: Database, keywords: ["storage", "db"] },
  { name: "Rocket", Icon: Rocket, keywords: ["launch", "start"] },
  { name: "Zap", Icon: Zap, keywords: ["fast", "flash"] },
  { name: "Wifi", Icon: Wifi, keywords: ["network", "internet"] },
  { name: "Cloud", Icon: Cloud, keywords: ["storage", "deploy"] },
  { name: "Sun", Icon: Sun, keywords: ["light", "day"] },
  { name: "Moon", Icon: Moon, keywords: ["night", "dark"] },
  { name: "Map", Icon: Map, keywords: ["location", "geo"] },
  { name: "Compass", Icon: Compass, keywords: ["nav", "direction"] },
  { name: "GitBranch", Icon: GitBranch, keywords: ["git", "branch"] },
  { name: "Github", Icon: Github, keywords: ["code", "repo"] },
  { name: "Linkedin", Icon: Linkedin, keywords: ["social"] },
  { name: "Twitter", Icon: Twitter, keywords: ["social", "x"] },
];

export function getLucideIconOption(name?: string | null): LucideIconOption | null {
  if (!name) return null;
  return LUCIDE_ICON_OPTIONS.find((opt) => opt.name === name) || null;
}


